image: node:12.14.1

stages:
  - build
  - deploy

##
# Import CI Jobs
##
include:
  - project: 'thepuzzlers-org/websites/ci-templates'
    ref: 'master'
    file: 'ssh-deploy.yml'

  # build_gatsby job is executed automatically
  - project: 'thepuzzlers-org/websites/ci-templates'
    ref: 'master'
    file: 'build-gatsby.yml'

deploy_public_folder:
  stage: deploy
  extends: .ssh_deploy
  variables:
    DOMAIN: '' # Add production url here! e.g. thepuzzlers.io or shop.thetrainee.co
  needs: [build_gatsby]
  # only deploy to production when pushed to master branch
  only:
    - master
